import { reportVariant } from './reportVisuals';

export type ReportArticleSource = {
  id: string;
  title: string;
  url: string;
  publisher?: string;
  publishedAt?: string;
  imageUrl?: string;
  description?: string;
  topic?: 'nutrition' | 'training' | 'recovery' | 'habits';
};
export type ReportReading = ReportArticleSource & { kind: 'reference' | 'reading' };

// Publisher pages checked September 2026. These are optional reading, not
// additional citations or personalized prescriptions generated by the report.
const nutrition: ReportArticleSource[] = [
  { id: 'reading-fibre', title: 'Bring more fibre to everyday meals', url: 'https://www.nhs.uk/live-well/eat-well/digestive-health/how-to-get-more-fibre-into-your-diet/', publisher: 'NHS', description: 'Practical ideas using vegetables, pulses, fruit and whole grains.', topic: 'nutrition' },
  { id: 'reading-protein', title: 'Explore your protein options', url: 'https://nutritionsource.hsph.harvard.edu/what-should-you-eat/protein/', publisher: 'Harvard · The Nutrition Source', description: 'A closer look at plant and animal protein foods.', topic: 'nutrition' },
  { id: 'reading-prep', title: 'Make meal prep work for you', url: 'https://nutritionsource.hsph.harvard.edu/meal-prep/', publisher: 'Harvard · The Nutrition Source', description: 'Plan, shop and prepare food around your own schedule.', topic: 'nutrition' },
  { id: 'reading-drinks', title: 'Rethink your everyday drinks', url: 'https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/water-drinks-nutrition/', publisher: 'NHS', description: 'A guide to hydration and choosing drinks throughout the day.', topic: 'nutrition' },
  { id: 'reading-labels', title: 'Make sense of food labels', url: 'https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/how-to-read-food-labels/', publisher: 'NHS', description: 'Understand nutrition panels and compare packaged foods.', topic: 'nutrition' },
  { id: 'reading-plate', title: 'Build a balanced plate', url: 'https://nutritionsource.hsph.harvard.edu/healthy-eating-plate/', publisher: 'Harvard · The Nutrition Source', description: 'Explore how different food groups can fit together in a meal.', topic: 'nutrition' },
];
const movement: ReportArticleSource[] = [
  { id: 'reading-activity', title: 'Balance movement and strength', url: 'https://www.cdc.gov/physical-activity-basics/guidelines/adults.html', publisher: 'CDC', description: 'An overview of aerobic activity and muscle-strengthening guidance for adults.', topic: 'training' },
  { id: 'reading-strength', title: 'Start with simple strength exercises', url: 'https://www.nhs.uk/live-well/exercise/strength-exercises/', publisher: 'NHS', description: 'Gentle movements to explore at home, with illustrated instructions.', topic: 'training' },
  { id: 'reading-flexibility', title: 'Explore gentle flexibility exercises', url: 'https://www.nhs.uk/live-well/exercise/flexibility-exercises/', publisher: 'NHS', description: 'Simple stretches for your neck, shoulders and lower body.', topic: 'recovery' },
  { id: 'reading-sleep', title: 'Understand your sleep habits', url: 'https://www.cdc.gov/sleep/about/index.html', publisher: 'CDC', description: 'Learn about sleep quality and habits that support better sleep.', topic: 'recovery' },
];
export const REPORT_READING_LIBRARY = { diet: nutrition, weekly: [...movement, nutrition[1], nutrition[2], nutrition[3]] };

function articleUrlKey(url: string) {
  return url.replace(/[?#].*$/, '').replace(/\/+$/, '');
}

export function buildReportReading(sources: ReportArticleSource[], family: 'diet' | 'weekly', reportKey: string): ReportReading[] {
  const seen = new Set<string>();
  const articles: ReportReading[] = [];
  const add = (source: ReportArticleSource, kind: ReportReading['kind']) => {
    if (!source || !source.title?.trim() || typeof source.url !== 'string' || !/^https:\/\//i.test(source.url)) return;
    const key = articleUrlKey(source.url);
    if (seen.has(key)) return;
    seen.add(key);
    articles.push({ ...source, kind });
  };
  sources.forEach(source => add(source, 'reference'));
  const pool = REPORT_READING_LIBRARY[family];
  const start = reportVariant(reportKey, pool.length);
  [...pool.slice(start), ...pool.slice(0, start)].forEach(source => {
    if (articles.length < 6) add(source, 'reading');
  });
  return articles;
}
